### PR TITLE
Add other missing imports

### PR DESCRIPTION
**Pull request by waifod**
We try to fix the workflow failures by adding missing imports.

### CODE REVIEW

**Comment by waifod** [comment]
Alright, it looks like the build issues are fixed, but now there's a test failure due to an exception being thrown.

From what I see, the tests do not expect failures, and since locally they were running fine (when they were running), this failure may come from some undefined behavior. Hooray!

**Review by lluiscamino — APPROVED** [review]

**Comment by lluiscamino** [comment]
Tests failure is so weird! It's failing in this [line](https://github.com/lluiscamino/em/blob/main/src/em/runtime/Interpreter.cpp#L97). It's like if the program was trying to do a binary operation with an identifier as the token (e.g. `a IDENTIFIER b` instead of `a = b`).

We should add a try catch and log which test failed and try to debug from there. I can work on this when I have time, if you don't want to take a look at it. Or if you want, go ahead!

**Comment by waifod** [comment]
I agree on adding logs, but I don't like exceptions as they are generally considered bad practices.

As I said already, we should also add a testing framework to facilitate things.

**Comment by lluiscamino** [comment]
Yeah, eventually I wanted to add some kind of errors logger than saves all of the parsing or execution errors and displays them to the user. So that if there's multiple errors in a problem we log all of them instead of exiting the program in the first found error.

**Pull request merged**
